### ISSUE TITLE
Recent highways missing from OSM layer

### ISSUE THREAD

**Issue by lxbarth** [mapbox/tigeralignment#7]
@Rub21 

I just found residential highways on that appear as TIGER12-only (no OSM) on the tigeralignment app, but when I look at OSM, they do appear. They're residential roads and have been created on Nov 2 2012.
- Are we not rendering `highhway=residential` on our blue OSM layer? 
- Are we using an extract older than Nov 2 2012 of OSM?
- What else could be going on?

![](http://cl.ly/image/1q0y1B44062O/Screen%20Shot%202013-01-25%20at%203.09.43%20PM.png)

On our app: http://mapbox.com/tigeralignment/#15.00/37.9911/-78.2035  
On OSM: http://www.openstreetmap.org/?lat=37.9911&lon=-78.2035&zoom=15

**Comment by Rub21** [comment]
Close this!!!
